languge: python
before_install:
  - uname -a
  - sudo apt install -y linux-headers-generic
  - sudo apt install -y virtualbox-dkms
  - sudo dpkg-reconfigure virtualbox-dkms
  - sudo apt-get install -y virtualbox --fix-missing
  - VBoxManage --version
install:
  - sudo apt install -y vagrant curl
  - vagrant --version
script:
  - vagrant up
  - curl -I localhost:5000
addons:
  apt:
    update: true
