languge: python
dist: xenial
before_install:
  - sudo apt-get update && sudo apt-get dist-upgrade && sudo apt-get autoremove
  - sudo apt-get -y install gcc make linux-headers-$(uname -r) dkms
  - wget -q https://www.virtualbox.org/download/oracle_vbox_2016.asc -O- | sudo apt-key add -
  - wget -q https://www.virtualbox.org/download/oracle_vbox.asc -O- | sudo apt-key add -
  - sudo sh -c 'echo "deb http://download.virtualbox.org/virtualbox/debian $(lsb_release -sc) contrib" >> /etc/apt/sources.list'
  - sudo apt-get update
  - sudo apt-get install virtualbox-5.2 curl
  - VBoxManage --version
  - sudo wget https://releases.hashicorp.com/vagrant/2.2.2/vagrant_2.2.2_x86_64.deb
  - sudo dpkg -i https://releases.hashicorp.com/vagrant/2.2.2/vagrant_2.2.2_x86_64.deb
  - sudo vagrant plugin install vagrant-vbguest
install:
  - travis_wait 40 vagrant up --provider=virtualbox
  - VBoxManage list vms -l
script:

  - curl -I localhost:8080
addons:
  apt:
    update: true
